baseURL = "https://packs.nebari.dev/"
languageCode = "en-us"
title = "Nebari Software Packs"

[module]
  [[module.imports]]
    path = "github.com/nebari-dev/nebari-hugo-theme"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  logoLink = "https://packs.nebari.dev/"
  description = "Documentation portal for official Nebari software packs."
